export type Translation = {
  badge: string;
  heroTitle: string;
  heroSubtitle: string;
  signedInAs: string;
  signInWithGoogle: string;
  guest: string;
  signOut: string;
  preferencesTitle: string;
  languageLabel: string;
  languageOptions: { en: string; he: string };
  allSectors: string;
  companiesCount: (count: number) => string;
  searchPlaceholder: string;
  loadingCompanies: string;
  loadingNotes: string;
  noNotes: string;
  private: string;
  public: string;
  keepPrivate: string;
  addNote: string;
  notePlaceholder: string;
  markPrivate: string;
  saveNote: string;
  saving: string;
  deleting: string;
  save: string;
  edit: string;
  delete: string;
  cancel: string;
  viewNotes: string;
  hideNotes: string;
  description: string;
  describing: string;
  aiDescription: string;
  descriptionError: string;
  website: string;
  employeesLabel: string;
  companyIdLabel: string;
  companiesLabel: string;
  loadingNotesButton: string;
  errors: {
    loadCompanies: string;
    loadNotes: string;
    createNote: string;
    updateNote: string;
    deleteNote: string;
    summarize: string;
  };
};
